import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, dirname, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import {
  directory,
  workspace,
  hash,
  readJson,
  pins,
  listJson,
  currentProvenance,
  recordPath,
  moduleParts,
  resolveCommit,
  tree,
  regenerate,
  proposeRecord,
  safeInside,
} from './replay-lib.mjs';

const same = (left, right) => JSON.stringify(left) === JSON.stringify(right);

/** Read native files and Git objects; write nothing. Pending review is not a pass. */
export async function checkRecords(selectedModule) {
  const provenance = currentProvenance();
  const current = provenance.modules.filter(
    (item) => !selectedModule || item.module === selectedModule,
  );
  if (selectedModule && !current.length) throw new Error(`No native module: ${selectedModule}`);
  const records = listJson(resolve(directory, 'records')).map((path) => ({
    path,
    record: readJson(path),
  }));
  const recordErrors = [];
  const seenRecords = new Set();
  for (const { path, record } of records) {
    try {
      if (path !== recordPath(record.module)) recordErrors.push(`Misplaced record: ${path}`);
      if (seenRecords.has(record.module)) recordErrors.push(`Duplicate record: ${record.module}`);
      seenRecords.add(record.module);
    } catch (error) {
      recordErrors.push(error.message);
    }
  }
  const results = [];
  for (const native of current) {
    const path = recordPath(native.module);
    if (!existsSync(path)) {
      results.push({
        module: native.module,
        passed: false,
        errors: ['No per-module review record.'],
        review: 'pending',
      });
      continue;
    }
    const record = readJson(path);
    const errors = [];
    if (record.schemaVersion !== 1 || record.module !== native.module)
      errors.push('Invalid or misplaced record.');
    const { repository } = moduleParts(native.module);
    if (
      record.repository !== repository ||
      record.pinnedCommit !== provenance.pins[repository].commit
    )
      errors.push('The record does not use the current pinned repository commit.');
    if (record.nativeSha256 !== native.currentSha256)
      errors.push(
        'Native file differs from its recorded hash. Review the change; do not refresh the record without review.',
      );
    if (!same(record.externalInputs, native.externalInputs))
      errors.push(
        'Declared external package inputs, version, lockfile, or license changed. Run the separate external generator check and review the record.',
      );
    if (
      !same(
        record.sources?.map(({ path, blob, mode }) => ({ path, blob, mode })),
        native.upstreamSources.map(({ path, blob, mode }) => ({ path, blob, mode })),
      )
    )
      errors.push('Pinned source paths or exact Git blobs differ from the record.');
    let replay;
    try {
      replay = await regenerate(native.module, provenance.pins[repository].commit);
      if (!!record.replay !== !!replay)
        errors.push('The recipe presence differs from the recorded replay.');
      if (replay) {
        if (!same(record.replay?.toolchain, replay.toolchain))
          errors.push(
            'The generator, override, formatter, dependency version, or lockfile changed.',
          );
        if (record.replay?.generatedSha256 !== hash(replay.generated))
          errors.push('The unpatched generated bytes differ from the replay record.');
        if (record.replay?.finalSha256 !== hash(replay.code))
          errors.push('The final generated bytes differ from the replay record.');
        if (hash(replay.code) !== native.currentSha256)
          errors.push('Regeneration does not equal the live native file. No file was replaced.');
      }
    } catch (error) {
      errors.push(error.message);
    }
    results.push({
      module: native.module,
      passed: errors.length === 0,
      errors,
      review: record.review?.state ?? 'pending',
      acceptedBehavior: record.review?.acceptedBehavior === true,
      pendingSourceReviews:
        record.sources?.filter((source) => source.review === 'pending').length ?? 0,
      replayEquality: replay ? hash(replay.code) === native.currentSha256 : null,
      manualException: record.manualException,
    });
  }
  const extraRecords = records
    .filter(({ record }) => !provenance.modules.some(({ module }) => module === record.module))
    .map(({ path }) => relative(workspace, path));
  const result = {
    schemaVersion: 1,
    mode: 'read-only-replay-and-record-check',
    passed:
      results.every((item) => item.passed) &&
      extraRecords.length === 0 &&
      recordErrors.length === 0,
    nativeModules: results.length,
    exactReplays: results.filter((item) => item.replayEquality === true).length,
    pendingModules: results.filter((item) => item.review === 'manual-review-pending').length,
    acceptedBehaviorModules: results.filter((item) => item.acceptedBehavior).length,
    pendingSourceReviews: results.reduce((count, item) => count + item.pendingSourceReviews, 0),
    fullMigrationAccepted: false,
    extraRecords,
    recordErrors,
    results,
    note: 'passed means records have not drifted and selected replay outputs match. It does not accept pending modules, behavior, tests, or pixels.',
  };
  return result;
}

function diff(left, right) {
  try {
    return execFileSync(
      'git',
      ['diff', '--no-index', '--no-ext-diff', '--no-textconv', '--', left, right],
      { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
    );
  } catch (error) {
    if (error.status === 1) return error.stdout;
    throw error;
  }
}

/** Only a newly allocated temporary directory can receive candidate artifacts. */
export async function makeCandidate(repository, reference) {
  const commit = resolveCommit(repository, reference);
  const pinnedCommit = pins()[repository].commit;
  const check = await checkRecords();
  if (!check.passed)
    throw new Error(
      'Current records have drifted. Run `node tooling/upstream/replay.mjs check` and review the errors before generating a candidate.',
    );
  const impact = JSON.parse(
    execFileSync(
      process.execPath,
      [resolve(directory, 'impact.mjs'), 'compare', repository, commit],
      { encoding: 'utf8', maxBuffer: 100 * 1024 * 1024 },
    ),
  );
  if (!impact.localState.trackedOriginalsUnchanged)
    throw new Error(
      'Original tracked source files differ from the pinned baseline. Review them first.',
    );
  const scratch = await mkdtemp(resolve(tmpdir(), 'solid-cn-upstream-'));
  const save = async (path, content) => {
    const target = safeInside(scratch, path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, content, { flag: 'wx' });
    return target;
  };
  const entries = tree(repository, commit);
  const records = listJson(resolve(directory, 'records'))
    .map(readJson)
    .filter((record) => record.repository === repository);
  const modules = [];
  for (const record of records) {
    const sources = record.sources.map((source) => ({
      path: source.path,
      pinnedBlob: source.blob,
      candidateBlob: entries.get(source.path)?.blob ?? null,
      changed: source.blob !== entries.get(source.path)?.blob,
      baselineReview: source.review,
      candidateReview:
        source.blob === entries.get(source.path)?.blob
          ? 'unchanged; prior review scope only'
          : 'pending',
    }));
    const mappedChanges = impact.changes.filter((change) =>
      change.directModules.includes(record.module),
    );
    const result = {
      module: record.module,
      pinnedNativeSha256: record.nativeSha256,
      sources,
      newlyMappedPaths: mappedChanges
        .map((change) => change.path)
        .filter((path) => !record.sources.some((source) => source.path === path)),
      review: 'pending',
      acceptedBehavior: false,
      manualException: record.manualException,
      generated: false,
    };
    try {
      const baseline = await regenerate(record.module, pinnedCommit);
      const candidate = await regenerate(record.module, commit);
      if (candidate) {
        const current = readFileSync(resolve(workspace, record.module));
        const baselinePath = await save(`baseline/${record.module}`, baseline.code);
        const candidatePath = await save(`candidate/${record.module}`, candidate.code);
        const currentPath = await save(`current/${record.module}`, current);
        const generatedPath = await save(`unpatched/${record.module}`, candidate.generated);
        const fromBaseline = await save(
          `diffs/${record.module}.upstream.diff`,
          diff(baselinePath, candidatePath),
        );
        const fromCurrent = await save(
          `diffs/${record.module}.native.diff`,
          diff(currentPath, candidatePath),
        );
        result.generated = true;
        result.candidateSha256 = hash(candidate.code);
        result.equalsCurrentNative = hash(candidate.code) === hash(current);
        result.equalsPinnedReplay = candidate.code === baseline.code;
        result.overrides = candidate.overrides;
        result.toolchain = candidate.toolchain;
        result.artifacts = {
          baselinePath,
          candidatePath,
          currentPath,
          generatedPath,
          fromBaseline,
          fromCurrent,
        };
      }
    } catch (error) {
      result.generationError = error.message;
    }
    modules.push(result);
  }
  const report = {
    schemaVersion: 1,
    mode: 'isolated-candidate-review',
    repository,
    suppliedRef: reference,
    pinnedCommit,
    candidateCommit: commit,
    scratch,
    outputOnlyInNewTemporaryDirectory: true,
    originalOrNativeFilesChanged: false,
    baselineChanged: false,
    automaticAcceptance: false,
    generatedModules: modules.filter((module) => module.generated).length,
    generationErrors: modules.filter((module) => module.generationError).length,
    impact,
    modules,
    nextStep:
      'Review exact source blobs, diffs, overrides, and all pending modules. Run unchanged tests and browser/visual checks before a separate deliberate source or acceptance-record update. This tool does not apply changes.',
  };
  const reportPath = await save('report.json', JSON.stringify(report, null, 2) + '\n');
  await save(
    'README.md',
    `# Upstream candidate review\n\nRepository: ${repository}\n\nPinned commit: ${pinnedCommit}\n\nCandidate commit: ${commit}\n\nThis directory contains generated candidates and review data only. Nothing was applied.\n\nOpen report.json. Review diffs/ for generated modules. The current/ files are comparison snapshots, not generators. All manual implementations remain review-pending. Exact generated bytes do not prove behavior or pixel parity.\n`,
  );
  return { ...report, reportPath };
}

async function main() {
  const [command = 'check', ...args] = process.argv.slice(2);
  if (command === 'check') {
    if (args.length && (args.length !== 2 || args[0] !== '--module'))
      throw new Error('Usage: replay.mjs check [--module <native-module>]');
    const report = await checkRecords(args[1]);
    console.log(JSON.stringify(report, null, 2));
    if (!report.passed) process.exitCode = 1;
  } else if (command === 'candidate') {
    if (args.length !== 2)
      throw new Error('Usage: replay.mjs candidate <base-ui|shadcn-ui> <existing-local-ref>');
    const report = await makeCandidate(args[0], args[1]);
    console.log(
      JSON.stringify(
        {
          reportPath: report.reportPath,
          scratch: report.scratch,
          candidateCommit: report.candidateCommit,
          generatedModules: report.generatedModules,
          generationErrors: report.generationErrors,
          applied: false,
        },
        null,
        2,
      ),
    );
    if (report.generationErrors) process.exitCode = 1;
  } else if (command === 'propose-record') {
    if (args.length !== 1) throw new Error('Usage: replay.mjs propose-record <native-module>');
    const native = currentProvenance().modules.find((item) => item.module === args[0]);
    if (!native) throw new Error(`No native module: ${args[0]}`);
    console.log(JSON.stringify(await proposeRecord(native), null, 2));
  } else
    throw new Error(
      'Commands: check, candidate, propose-record. No command applies or accepts source changes.',
    );
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href)
  main().catch((error) => {
    console.error(error.stderr?.toString().trim() || error.message);
    process.exitCode = 1;
  });
